tokosidia/tokosidia/Controllers/CustomerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Model.Tokosidia;
using ViewModel.Tokosidia;
using Repo.Tokosidia;

namespace tokosidia.Controllers
{
    [Tokosidia.SessionCheck.SessionCheck]
    public class CustomerController : Controller
    {
        // GET: Customer
        public ActionResult Index()
        {
            if (Session["name"] == null)
            {
                return Redirect("~/Login/Login/");
            }
            else
            {
                List<VMCustomer> listCustomer = new List<VMCustomer>();
                listCustomer = CustomerRepo.getAllData();
                return View(listCustomer);
            }
        }

        //view Add data customer
        public ActionResult Create()
        {
            ViewBag.ListProvinsi = CustomerRepo.getAllDataPovinsi();
            ViewBag.ListKota = new List<Kota>();
            ViewBag.listKecamatan = new List<Kecamatan>();
            ViewBag.listKelurahan = new List<Kelurahan>();
            //List<Provinsi> listProvinsi = new List<Provinsi>();
            //listProvinsi = CustomerRepo.getAllDataPovinsi();
            //ViewData["provinsi"] = listProvinsi;

            return View();
        }

        [HttpPost]
        //Post add customer
        public ActionResult Create(Customer customers)
        {
            string result = CustomerRepo.createData(customers);

            if (result == "ok")
            {
                return Json(new { message = "Berhasil" }, JsonRequestBehavior.AllowGet);
            }
            else if (result == "sameemail")
            {
                return Json(new { message = "Gagal, email sudah ada di database" }, JsonRequestBehavior.AllowGet);
            }
            else if (result == "sametelp")
            {
                return Json(new { message = "Gagal, nomor telpon sudah ada di database" }, JsonRequestBehavior.AllowGet);
            }
            else if (result == "sameidentitas")
            {
                return Json(new { message = "Gagal, nomor identitas sudah ada di database" }, JsonRequestBehavior.AllowGet);
            }
            else
            {
                return Json(new { message = "Gagal" }, JsonRequestBehavior.AllowGet);
            }
        }

        public JsonResult getListKota(string Kode_Provinsi)
        {
            return Json(CustomerRepo.getListKota(Kode_Provinsi), JsonRequestBehavior.AllowGet);
        }
        public JsonResult getListKecamatan(string Kode_Kota)
        {
            return Json(CustomerRepo.getListKecamatan(Kode_Kota), JsonRequestBehavior.AllowGet);
        }
        public JsonResult getListKelurahan(string Kode_Kecamatan)
        {
            return Json(CustomerRepo.getListKelurahan(Kode_Kecamatan), JsonRequestBehavior.AllowGet);
        }

        public ActionResult Edit(int id)
        {
            Customer customers = CustomerRepo.getDataById(id);
            //customers = CustomerRepo.getDataById(id);

            //ViewBag.listGender = CustomerRepo.getDataGeneral("gender");
            //ViewBag.listIdentityType = CustomerRepo.getDataGeneral("gender");
            ViewBag.listProvinsi = CustomerRepo.getAllDataPovinsi();

            if (customers.KODE_PROVINSI != null)
            {
                ViewBag.listKota = CustomerRepo.getListKota(customers.KODE_PROVINSI);
            }
            if (customers.KODE_KOTA != null)
            {
                ViewBag.listKecamatan = CustomerRepo.getListKecamatan(customers.KODE_KOTA);
            }
            if (customers.KODE_KECAMATAN != null)
            {
                ViewBag.listKelurahan = CustomerRepo.getListKelurahan(customers.KODE_KECAMATAN);
            }

            return View(customers);
        }

        [HttpPost]
        public ActionResult Edit(Customer customers)
        {
            string result = CustomerRepo.updateData(customers);

            if (result == "ok")
            {
                return Json(new { message = "Berhasil" }, JsonRequestBehavior.AllowGet);
            }
            else
            {
                return Json(new { message = "Gagal" }, JsonRequestBehavior.AllowGet);
            }
        }
        [HttpPost]
        public ActionResult Delete(int id)
        {

            string result = CustomerRepo.deleteData(id);

            if (result == "ok")
            {
                return Json(new { hasil = "berhasil" }, JsonRequestBehavior.AllowGet);
            }
            else
            {
                return Json(new { hasil = "gagal" }, JsonRequestBehavior.AllowGet);
            }
        }
    }
}

tokosidia/tokosidia/Views/Customer/Create.cshtml
@using Model.Tokosidia;

@{
    List<Provinsi> _listProvinsi = (List<Provinsi>)ViewData["provinsi"];
}

@{
    Layout = null;
    //ViewBag.Title = "Create";
}
<h2>Create</h2>

@using (Html.BeginForm("Create", "Customer", FormMethod.Post, new { id = "form-create" }))
{

    <div class="form-group">
        <label>No Identitas</label>
        <input type="text" id="NO_INDENTITAS" class="form-control" name="NO_INDENTITAS" />
    </div>
    <div class="form-group">
        <label>Nama</label>
        <input type="text" id="NAMA" class="form-control" name="NAMA" />
    </div>
    <div class="form-group">
        <label>No Telepon</label>
        <input type="text" id="NO_TLP" class="form-control" name="NO_TLP" />
    </div>
    <div class="form-group">
        <label>Email</label>
        <input type="text" id="EMAIL" class="form-control" name="EMAIL" />
    </div>
    <div class="form-group">
        <label>Alamat</label>
        <input type="text" id="ALAMAT" class="form-control" name="ALAMAT" />
    </div>
    <div class="form-group">
        <label>Gender</label>
        @*<input type="text" id="GENDER" class="form-control" name="GENDER" />*@
        <select class="form-control" id="GENDER" name="GENDER">
            <option value="1">Perempuan</option>
            <option value="2" selected>Laki-Laki</option>
        </select>
    </div>
    <div class="form-group">
        <label>Provinsi</label>
        @Html.DropDownList("KODE_PROVINSI", new SelectList(ViewBag.listProvinsi, "Kode_Provinsi", "Nama_Provinsi"), "---Pilih---", new { @class = "form-control" })
        @*<select class="form-control" id="KODE_PROVINSI" name="KODE_PROVINSI">
            <option value="">---Pilih---</option>

            @{
                if (_listProvinsi.Count > 0 && _listProvinsi != null)
                    {
                        foreach (var item in _listProvinsi)
                        {
                            <option value="@item.Kode_Provinsi">@item.Nama_Provinsi</option>
                        }
                    }
            }

        </select>*@
    </div>
    <div class="form-group">
        <label>Kota</label>
        @Html.DropDownList("KODE_KOTA", new SelectList(ViewBag.listKota, "kode_kota", "Nama_Kota"), "--Pilih--", new {@class="form-control" })
    </div>
    <div class="form-group">
        <label>Kecamatan</label>
        @Html.DropDownList("KODE_KECAMATAN", new SelectList(ViewBag.listKecamatan, "Kode_Kecamatan", "Nama_Kecamatan"), "--Pilih--", new {@class="form-control" })
    </div>
    <div class="form-group">
        <label>Kelurahan</label>
        @Html.DropDownList("KODE_KELURAHAN", new SelectList(ViewBag.listKelurahan, "Kode_Kelurahan", "Nama_Kelurahan"), "--Pilih--", new { @class = "form-control" })
    </div>
    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
    <button type="submit" id="btn-add" class="btn btn-primary">Submit</button>
}

<script>
    $(function () {
        $("#form-create").validate({
            errorClass: 'errors',
            rules: {
                NO_INDENTITAS: {
                    required: true

                },
                NAMA: {
                    required: true
                },
                NO_TLP: {
                    required: true,
                    number: true
                },
                EMAIL: {
                    required: true,
                    email: true
                },
                ALAMAT: {
                    required: true
                }
            },
            messages: {
                NO_INDENTITAS: {
                    required: "Please enter your No Indentitas"
                },
                NAMA: {
                    required: "Please enter your nama"
                },
                NO_TLP: {
                    required: "Please enter your No Telpon",
                    number: "Please provide a numeric value"
                },
                EMAIL: {
                    required: "Please enter your Email",
                    email: "Please enter correct Email"
                },
                ALAMAT: {
                    required: "Please enter your Alamat"
                }
            },

            submitHandler: function (form) {
                var dataForm = $(form).serialize();
                //debugger;
                $.ajax({
                    url: '/Customer/Create',
                    data: dataForm,
                    method: 'post',
                    dataType: "json",
                    success: function (response) {
                        if (response.message == "Berhasil") {
                            alert(response.message);
                            window.location.reload();
                        }
                        else {
                            alert(response.message);
                        }
                    }
                });
            }
        });
    });

    $("#KODE_PROVINSI").change(function () {
        var kd_prov = $(this).val();

        $.ajax({
            url: '/Customer/getListKota',
            dataType: 'json',
            data: { Kode_Provinsi: kd_prov },
            success: function (hasil) {
                $("#KODE_KOTA").empty();
                $("#KODE_KOTA").append("<option value=''>---Pilih---</option>");
                $.each(hasil, function (index, hasil) {
                    $("#KODE_KOTA").append("<option value='" + hasil.Kode_Kota + "'>" + hasil.Nama_Kota + "</option>");
                })
            }
        })
    })
    $("#KODE_KOTA").change(function () {
        var kd_kota = $(this).val();

        $.ajax({
            url: '/Customer/getListKecamatan',
            dataType: 'json',
            data: { Kode_Kota: kd_kota },
            success: function (hasil) {
                $("#KODE_KECAMATAN").empty();
                $("#KODE_KECAMATAN").append("<option value=''>--Pilih Kecamatan--</option>");
                $.each(hasil, function (index, hasil) {
                    $("#KODE_KECAMATAN").append("<option value='" + hasil.Kode_Kecamatan + "'>" + hasil.Nama_Kecamatan + "<option>");
                })
            }
        })
    })

    $("#KODE_KECAMATAN").change(function () {
        var kd_kecamatan = $(this).val();

        $.ajax({
            url: '/Customer/getListKelurahan',
            dataType: 'json',
            data: { Kode_Kecamatan: kd_kecamatan },
            success: function (hasil) {
                $("#KODE_KELURAHAN").empty();
                $("#KODE_KELURAHAN").append("<option value=''>--Pilih Kelurahan--</option>");
                $.each(hasil, function (index, hasil) {
                    $("#KODE_KELURAHAN").append("<option value='" + hasil.Kode_Kelurahan + "'>" + hasil.Nama_Kelurahan + "</option>");
                })
            }
        })
    })

</script>

tokosidia/tokosidia/Views/Customer/Edit.cshtml
@model Model.Tokosidia.Customer
@{
    Layout = null;
    ViewBag.Title = "Edit";
}
<h2>Edit</h2>

@using (Html.BeginForm("Edit", "Customer", FormMethod.Post, new { id = "form-edit" }))
{
    @Html.HiddenFor(a => a.ID)
    <div class="form-group">
        <label>No Identitas</label>
        <input type="text" id="NO_INDENTITAS" class="form-control" name="NO_INDENTITAS" value="@Model.NO_INDENTITAS" />
    </div>
    <div class="form-group">
        <label>Nama</label>
        <input type="text" id="NAMA" class="form-control" name="NAMA" value="@Model.NAMA" />
    </div>
    <div class="form-group">
        <label>No Telepon</label>
        <input type="text" id="NO_TLP" class="form-control" name="NO_TLP" value="@Model.NO_TLP" />
    </div>
    <div class="form-group">
        <label>Email</label>
        <input type="text" id="EMAIL" class="form-control" name="EMAIL" value="@Model.EMAIL" />
    </div>
    <div class="form-group">
        <label>Alamat</label>
        <input type="text" id="ALAMAT" class="form-control" name="ALAMAT" value="@Model.ALAMAT" />
    </div>
    <div class="form-group">
        <label>Gender</label>
        <input type="text" id="GENDER" class="form-control" name="GENDER" value="@Model.GENDER" />
    </div>
    <div class="form-group">
        <label>Provinsi</label>
        @Html.DropDownList("KODE_PROVINSI", new SelectList(ViewBag.listProvinsi, "Kode_Provinsi", "Nama_Provinsi"), "---Pilih---", new { @class = "form-control" })
    </div>
    <div class="form-group">
        <label>Kota</label>
        @Html.DropDownList("KODE_KOTA", new SelectList(ViewBag.listKota, "kode_kota", "Nama_Kota"), "--Pilih--", new { @class = "form-control" })
    </div>
    <div class="form-group">
        <label>Kecamatan</label>
        @Html.DropDownList("KODE_KECAMATAN", new SelectList(ViewBag.listKecamatan, "Kode_Kecamatan", "Nama_Kecamatan"), "--Pilih--", new { @class = "form-control" })
    </div>
    <div class="form-group">
        <label>Kelurahan</label>
        @Html.DropDownList("KODE_KELURAHAN", new SelectList(ViewBag.listKelurahan, "Kode_Kelurahan", "Nama_Kelurahan"), "--Pilih--", new { @class = "form-control" })
    </div>
    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
    <button type="submit" id="btn-add" class="btn btn-primary">Submit</button>
}

<script>
    $(function () {
        $("#form-edit").validate({
            errorClass: 'errors',
            rules: {
                NO_INDENTITAS: {
                    required: true
                },
                NAMA: {
                    required: true
                },
                NO_TLP: {
                    required: true,
                    number: true
                },
                EMAIL: {
                    required: true
                },
                ALAMAT: {
                    required: true
                }
            },
            messages: {
                NO_INDENTITAS: {
                    required: "Please enter your No Indentitas"
                },
                NAMA: {
                    required: "Please enter your nama"
                },
                NO_TLP: {
                    required: "Please enter your No Telpon",
                    number: "Please provide a numeric value"
                },
                EMAIL: {
                    required: "Please enter your Email"
                },
                ALAMAT: {
                    required: "Please enter your Alamat"
                }
            },

            submitHandler: function (form) {
                var dataForm = $(form).serialize();
                //debugger;
                $.ajax({
                    url: '/Customer/Edit',
                    data: dataForm,
                    method: 'post',
                    dataType: "json",
                    success: function (response) {
                        if (response.message == "Berhasil") {
                            alert(response.message);
                            window.location.reload();
                        }
                        else {
                            alert(response.message);
                        }
                    }
                });
            }
        });
    });
    $("#KODE_PROVINSI").change(function () {
        var kd_prov = $(this).val();

        $.ajax({
            url: '/Customer/getListKota',
            dataType: 'json',
            data: { Kode_Provinsi: kd_prov },
            success: function (hasil) {
                $("#KODE_KOTA").empty();
                $("#KODE_KOTA").append("<option value=''>---Pilih---</option>");
                $.each(hasil, function (index, hasil) {
                    $("#KODE_KOTA").append("<option value='" + hasil.Kode_Kota + "'>" + hasil.Nama_Kota + "</option>");
                })
            }
        })
    })
    $("#KODE_KOTA").change(function () {
        var kd_kota = $(this).val();

        $.ajax({
            url: '/Customer/getListKecamatan',
            dataType: 'json',
            data: { Kode_Kota: kd_kota },
            success: function (hasil) {
                $("#KODE_KECAMATAN").empty();
                $("#KODE_KECAMATAN").append("<option value=''>--Pilih Kecamatan--</option>");
                $.each(hasil, function (index, hasil) {
                    $("#KODE_KECAMATAN").append("<option value='" + hasil.Kode_Kecamatan + "'>" + hasil.Nama_Kecamatan + "<option>");
                })
            }
        })
    })

    $("#KODE_KECAMATAN").change(function () {
        var kd_kecamatan = $(this).val();

        $.ajax({
            url: '/Customer/getListKelurahan',
            dataType: 'json',
            data: { Kode_Kecamatan: kd_kecamatan },
            success: function (hasil) {
                $("#KODE_KELURAHAN").empty();
                $("#KODE_KELURAHAN").append("<option value=''>--Pilih Kelurahan--</option>");
                $.each(hasil, function (index, hasil) {
                    $("#KODE_KELURAHAN").append("<option value='" + hasil.Kode_Kelurahan + "'>" + hasil.Nama_Kelurahan + "</option>");
                })
            }
        })
    })
</script>

tokosidia/tokosidia/Views/Customer/Index.cshtml
@model List<ViewModel.Tokosidia.VMCustomer>

@{
    ViewBag.Title = "Index";
}

<style>
    table {
        font-family: arial, sans-serif;
        border-collapse: collapse;
        width: 100%;
    }

    td, th {
        border: 1px solid #de8a8a;
        text-align: center;
        padding: 8px;
    }

    tr:nth-child(even) {
        background-color: #de8a8a;
    }
</style>
<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/bootstrap.min.js"></script>

<body>

    <h2>Index Customer</h2>

    <button id="id-btn-add" class="btn btn-primary">Add Data</button>
   
    <br><br>
    <table>
        <tr>

            <th>No Identitas</th>
            <th>Nama</th>
            <th>No Telpon</th>
            <th>Email</th>
            <th width="40%">Alamat</th>
            <th>Gender</th>
            <th>Action</th>
        </tr>

        <tbody>
            @foreach (var item in Model)
                {
                <tr>
                    <td>@item.NO_INDENTITAS</td>
                    <td>@item.NAMA</td>
                    <td>@item.NO_TLP</td>
                    <td>@item.EMAIL</td>
                    <td>@item.ALAMAT, @item.NAMA_PROVINSI, @item.NAMA_KOTA, @item.NAMA_KECAMATAN, @item.NAMA_KELURAHAN</td>
                    <td>
                        @{if (@item.GENDER == 1)
                            {
                            <p>Perempuan</p>
                            }
                            else if (@item.GENDER == 2)
                            {
                                <p>Laki - Laki</p>
                            }
                            else
                            {
                                <p>-</p>
                            }

                        }
                    </td>
                    <td>
                        <button class="btn btn-warning cls-edit" id="id-btn-edit" idcustomer="@item.ID">Edit</button>
                        <button class="btn btn-danger cls-del" idcustomer="@item.ID">Delete</button>
                    </td>
                </tr>
                }
        </tbody>

    </table>

    <!-- Modal -->
    <div class="modal fade bd-example-modal-sm" id="id-modal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header" id="id-header-mods">
                    <h5 class="modal-title" id="id-title-mods">Modal title</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body" id="id-body-mods">
                    ...
                </div>
                <div class="modal-footer" id="id-footer-mods">
                    @*<button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                        <button type="button" class="btn btn-primary">Save changes</button>*@
                </div>
            </div>
        </div>
    </div>

    <!-- Modal Delete -->
    <div class="modal fade bd-example-modal-sm" id="id-modal-delete" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header" id="id-header-mods">
                    <h5 class="modal-title" id="id-title-mods-delete">Modal title</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body" id="id-body-delete">
                    ...
                </div>
                <div class="modal-footer" id="id-footer-delete">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-primary" id="id-btn-delete">OK</button>
                </div>
            </div>
        </div>
    </div>
</body>
<script>
    var id_ForDelete = "";
    $("#id-btn-add").click(function () {
        //alert("Button Add call");

        $.ajax({
            url: '@Url.Action("Create", "Customer")',
            method: 'get',
            success: function (hasil) {
                $("#id-title-mods").html("Create");
                $("#id-body-mods").html(hasil);
                $("#id-modal").modal("show");
            }
        });
    });

    $(".cls-edit").click(function () {
        var ID = $(this).attr('idcustomer');
        $.ajax({
            url: '@Url.Action("Edit", "Customer")',
            method: 'get',
            data: { id: ID },
            success: function (tampil) {
                $("#id-title-mods").html("Edit");
                $("#id-body-mods").html(tampil);
                $("#id-modal").modal("show");
            }
        });
    })

    $('#id-btn-delete').on('hidden.bs.modal', function () {
        id_ForDelete = "";
    });

    $(".cls-del").click(function () {
        //debugger;
        id_ForDelete = $(this).attr('idcustomer');
        $("#id-title-mods-delete").html("Delete");
        $("#id-body-delete").html("Hapus ?");
        $("#id-modal-delete").modal("show");

        $("#id-btn-delete").click(function () {
            $.ajax({
                url: '@Url.Action("Delete", "Customer")',
                method: 'post',
                data: { id: id_ForDelete },
                success: function (tampil) {
                    if (tampil.hasil == "berhasil") {
                        window.location.reload();
                    }
                }
            })
        })
    })

</script>