tokosidia/tokosidia/Controllers/BarangController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Model.Tokosidia;
using ViewModel.Tokosidia;
using Repo.Tokosidia;
using PagedList;
using System.IO;

namespace tokosidia.Controllers
{
    [Tokosidia.SessionCheck.SessionCheck]
    public class BarangController : Controller
    {
        // GET: Barang
        public ActionResult Index(string searchString, string currentFilter, string sortOrder, int? page)
        {
            if (Session["name"] == null)
            {
                return Redirect("~/Login/Login/");
            }
            else
            {
                List<M_tbl_Barang> listBarang = new List<M_tbl_Barang>();
                listBarang = BarangRepo.getAllData();

                if (searchString != null)
                {
                    page = 1;
                }
                else
                {
                    searchString = currentFilter;
                }

                ViewBag.currentFilter = searchString;

                ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";

                if (!string.IsNullOrEmpty(searchString))
                {
                    listBarang = listBarang.Where(a => a.Nama_Barang.ToLower().Contains(searchString.ToLower())).ToList();
                }
                else if (sortOrder == "name_desc")
                {
                    listBarang = listBarang.OrderByDescending(a => a.Nama_Barang).ToList();
                }
                else if (sortOrder == null)
                {
                    listBarang = listBarang.OrderBy(a => a.Nama_Barang).ToList();
                }

                int pageSize = 10;
                int pageNumber = (page ?? 1);

                return View(listBarang.ToPagedList(pageNumber,pageSize));
            }
        }

        public ActionResult Edit(int id)
        {
            M_tbl_Barang Barang = new M_tbl_Barang();

            Barang = BarangRepo.getDataById(id);

            return View(Barang);
        }

        public ActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Create(M_tbl_Barang barang)
        {
            string result = BarangRepo.createData(barang);

            if (result == "ok")
            {
                return Json(new { message = "Berhasil" }, JsonRequestBehavior.AllowGet);
            }
            else
            {
                return Json(new { message = "Gagal" }, JsonRequestBehavior.AllowGet);
            }

            //return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult Edit(M_tbl_Barang barang)
        {

            //M_tbl_Barang barangLama = new M_tbl_Barang();

            string result = BarangRepo.updateData(barang);

            if (result == "ok")
            {
                return Json(new { message = "Berhasil" }, JsonRequestBehavior.AllowGet);
            }
            else
            {
                return Json(new { message = "Gagal" }, JsonRequestBehavior.AllowGet);
            }
            
            //return RedirectToAction("Index");
        }
        [HttpPost]
        public ActionResult Delete(int id)
        {

            string result = BarangRepo.deleteData(id);

            if (result == "ok")
            {
                return Json(new { hasil = "berhasil" }, JsonRequestBehavior.AllowGet);
            }
            else
            {
                return Json(new { hasil = "gagal" }, JsonRequestBehavior.AllowGet);
            }
        }

        public ActionResult Upload()
        {
            var file = Request.Files[0];
            var fileName = Path.GetFileName(file.FileName);

            string path = Path.Combine(AppDomain.CurrentDomain.BaseDirectory, "Images") + "\\" + fileName;

            file.SaveAs(path);

            FileStream fileStream = new FileStream(path, FileMode.Open, FileAccess.Read);
            byte[] data = new byte[(int)fileStream.Length];
            fileStream.Read(data, 0, data.Length);

            VMUpload upload = new VMUpload();

            upload.File_Name = fileName;
            upload.File_Url = path;

            return Json(new { upload, path = Convert.ToBase64String(data) }, JsonRequestBehavior.AllowGet);
        }
    }
}

tokosidia/tokosidia/Views/Barang/Create.cshtml
@{
    Layout = null;
    ViewBag.Title = "Create";
}
<h2>Create</h2>

@using (Html.BeginForm("Create", "Barang", FormMethod.Post, new { id = "form-create", enctype = "multipart/form/data" }))
{

    <div class="form-group">
        <label>Kode Barang</label>
        <input type="text" id="Kode_Barang" class="form-control" name="Kode_Barang" />
    </div>
        <div class="form-group">
            <label>Nama Barang</label>
            <input type="text" id="Nama_Barang" class="form-control" name="Nama_Barang" />
        </div>
        <div class="form-group">
            <label>Harga</label>
            <input type="text" id="Harga" class="form-control" name="Harga" />
        </div>
        <div class="form-group">
            <label>Qty</label>
            <input type="text" id="Qty" class="form-control" name="Qty" />
        </div>
        <div class="form-group">
            <label>Images</label>
            <input type="file" id="file" class="form-control" name="file" multiple="multiple" />
        </div>
        <div class="form-group" id="img-show" style="display:none">
        </div>
        <input type="hidden" id="img" name="img" />
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button type="submit" id="btn-add" class="btn btn-primary">Submit</button>
}

<script>
    var img_name = "";
    $("#file").change(function () {
        var fileData = new FormData();
        var files = $("#file").get(0).files;

        if (files.length > 0) {
            fileData.append("Images", files[0]);
        }
        $.ajax({
            url: '/Barang/Upload',
            data: fileData,
            method: 'post',
            dataType: 'json',
            processData: false,
            contentType: false,
            success: function (response) {
                debugger;
                alert("Berhasil");
                var imag = "<img "
                + "src='" + "data:image/jpg;base64,"
                + response.path + "' style='width:40%; height:40%'/>";

                $("#img").val(response.upload.File_Name);

                $("#img-show").html(imag)
                $("#img-show").show();
            }
        })
    })
    $(function () {
        $("#form-create").validate({
            errorClass: 'errors',
            rules: {
                Kode_Barang: {
                    required: true,
                    minlength: 7,
                    maxlength: 7
                },
                Nama_Barang: {
                    required: true,
                },
                Harga: {
                    required: true,
                    number: true
                },
                Qty: {
                    required: true,
                    number: true
                }
            },
            messages: {
                Kode_Barang: {
                    required: "Please enter your kode barang",
                    minlength: "your kode barang must be at least 7 character",
                    maxlength: "your kode barang must be 7 character"
                },
                Nama_Barang: {
                    required: "Please enter your nama barang"
                },
                Harga: {
                    required: "Please enter your harga",
                    number: "Please provide a numeric value"
                },
                Qty: {
                    required: "Please enter your qty",
                    number: "Please provide a numeric value"
                }
            },

            submitHandler: function (form) {
                var dataForm = $(form).serialize();
                //debugger;
                $.ajax({
                    url: '/Barang/Create',
                    data: dataForm,
                    method: 'post',
                    //title: 'Judul',
                    dataType: "json",
                    success: function (response) {
                        if (response.message == "Berhasil") {
                            alert(response.message);
                            window.location.reload();
                        }
                        else {
                            alert(response.message);
                        }
                    }
                });
            }
        });
    });
</script>

tokosidia/tokosidia/Views/Barang/Delete.cshtml
@model tokosidia.Models.M_tbl_Barang
@{
    Layout = null;
    ViewBag.Title = "Delete";
}

@using (Html.BeginForm("Delete", "Barang", FormMethod.Post, new { id = "form-edit" }))
{
    @Html.HiddenFor(a => a.id_Barang)
<button type="button" class="btn btn-secondary" data-dismiss="modal">Tidak</button>
<button type="submit" id="btn-add" class="btn btn-primary">Hapus</button>
}

tokosidia/tokosidia/Views/Barang/Edit.cshtml
@model Model.Tokosidia.M_tbl_Barang
@{

    Layout = null;
    //ViewBag.Title = "Edit";
}
<h2>Edit</h2>

@using (Html.BeginForm("Edit", "Barang", FormMethod.Post, new { id = "form-edit" }))
{
    @Html.HiddenFor(a=>a.id_Barang)
    <div class="form-group">
        <label>Kode Barang</label>
        <input type="text" id="Kode_Barang" class="form-control" value="@Model.Kode_Barang" name="Kode_Barang" />
    </div>
        <div class="form-group">
            <label>Nama Barang</label>
            <input type="text" id="Nama_Barang" class="form-control" value="@Model.Nama_Barang" name="Nama_Barang" />
        </div>
        <div class="form-group">
            <label>Harga</label>
            <input type="text" id="Harga" class="form-control" value="@Model.Harga" name="Harga" />
        </div>
        <div class="form-group">
            <label>Qty</label>
            <input type="text" id="Qty" class="form-control" value="@Model.Qty" name="Qty" />
        </div>
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button type="submit" id="btn-add" class="btn btn-primary">Submit</button>
}

<script>

    $(function () {
        $("#form-edit").validate({
            errorClass: 'errors',
            rules: {
                Kode_Barang: {
                    required: true,
                    minlength: 7,
                    maxlength: 7
                },
                Nama_Barang: {
                    required: true,
                },
                Harga: {
                    required: true,
                    number: true
                },
                Qty: {
                    required: true,
                    number: true
                }
            },
            messages: {
                Kode_Barang: {
                    required: "Please enter your kode barang",
                    minlength: "your kode barang must be at least 7 character",
                    maxlength: "your kode barang must be 7 character"
                },
                Nama_Barang: {
                    required: "Please enter your nama barang"
                },
                Harga: {
                    required: "Please enter your harga",
                    number: "Please provide a numeric value"
                },
                Qty: {
                    required: "Please enter your qty",
                    number: "Please provide a numeric value"
                }
            },

            submitHandler: function (form) {
                var dataForm = $(form).serialize();
                //debugger;
                $.ajax({
                    url: '/Barang/Edit',
                    data: dataForm,
                    method: 'post',
                    dataType: "json",
                    success: function (response) {
                        //alert(response.message);
                        if (response.message == "Berhasil") {
                            window.location.reload();
                        }
                        else {
                            alert(response.message);
                        }
                    }
                });
            }
        });
    });
</script>

tokosidia/tokosidia/Views/Barang/Index.cshtml
@model PagedList.IPagedList<Model.Tokosidia.M_tbl_Barang>
@using PagedList.Mvc;
<link href="~/Content/PagedList.css" rel="stylesheet" />

@{
    ViewBag.Title = "Index";
}

<h2>WELCOME IN YOUR BARANG TOKOSIDIA</h2>

<style>
    table {
        font-family: arial, sans-serif;
        border-collapse: collapse;
        width: 100%;
    }

    td, th {
        border: 1px solid #dddddd;
        text-align: center;
        padding: 8px;
    }

    tr:nth-child(even) {
        background-color: #dddddd;
    }
</style>
<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/bootstrap.min.js"></script>
<script src="~/Scripts/main.js"></script>

@*@Html.ActionLink("Add", "Create", "Barang");*@
@*<a href="@Url.Action("Create", "Barang")" class="btn btn-primary" >Add</a>*@

<button id="id-btn-add" class="btn btn-primary">Add</button>
<br>


@using (Html.BeginForm("Index", "Barang", FormMethod.Get, new {id= "form-barang" }))
{
    <input type="text" name="searchString" id="searchString" value="@ViewBag.currentFilter"/>
    <button value="Search" type="submit">Search</button>
    <button value="Reset" type="reset" id="id-reset">Reset</button>
}
<table>
    <tr>
        <th>Kode Barang</th>
        <th>
            @Html.ActionLink("Nama Barang", "Index", new { sortOrder = ViewBag.NameSortParm })
        </th>
        <th>Harga</th>
        <th>Qty</th>
        <th>Action</th>
    </tr>

    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.Kode_Barang</td>
                <td>@item.Nama_Barang</td>
                <td>@item.Harga</td>
                <td>@item.Qty</td>
                <td>
                    <button class="btn btn-warning cls-edit" id="id-btn-edit" idBarang="@item.id_Barang">Edit</button>
                    <button class="btn btn-danger cls-del" idBarang="@item.id_Barang">Delete</button>
                </td>
            </tr>
        }
    </tbody>

</table>
Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount

@Html.PagedListPager(Model, page => Url.Action("Index",
    new { page, currentFilter = ViewBag.CurrentFilter }))
@*new { page, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter }))*@
<!-- Modal -->
<div class="modal fade bd-example-modal-sm" id="id-modal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header" id="id-header-mods">
                <h5 class="modal-title" id="id-title-mods">Modal title</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body" id="id-body-mods">
                ...
            </div>
            <div class="modal-footer" id="id-footer-mods">
            </div>
        </div>
    </div>
</div>

<!-- Modal Delete -->
<div class="modal fade bd-example-modal-sm" id="id-modal-delete" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header" id="id-header-mods">
                <h5 class="modal-title" id="id-title-mods-delete">Modal title</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body" id="id-body-delete">
                ...
            </div>
            <div class="modal-footer" id="id-footer-delete">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <button type="submit" class="btn btn-primary" id="id-btn-delete">OK</button>
            </div>
        </div>
    </div>
</div>

<script>
    var id_ForDelete = "";
    //Jquery
    $("#id-btn-add").click(function () {
        //alert("Button Add call");

        $.ajax({
            url: '@Url.Action("Create", "Barang")',
            method: 'get',
            success: function (hasil) {
                $("#id-title-mods").html("Create");
                $("#id-body-mods").html(hasil);
                $("#id-modal").modal("show");
            }
        });

    });
    $(".cls-edit").click(function () {
        var id_barang = $(this).attr('idBarang');
        //debugger;
        $.ajax({
            url: '@Url.Action("Edit", "Barang")',
            method: 'get',
            data: { id: id_barang },
            success: function (tampil) {
                //debugger;
                $("#id-title-mods").html("Edit");
                $("#id-body-mods").html(tampil);
                $("#id-modal").modal("show");
            }
        });
    })

    $('#id-btn-delete').on('hidden.bs.modal', function () {
        id_ForDelete = "";
    });

    $(".cls-del").click(function () {
        //debugger;
        id_ForDelete = $(this).attr('idBarang');
        $("#id-title-mods-delete").html("Delete");
        $("#id-body-delete").html("Hapus ?");
        $("#id-modal-delete").modal("show");

        $("#id-btn-delete").click(function () {
            $.ajax({
                url: '@Url.Action("Delete", "Barang")',
                method: 'post',
                data: { id: id_ForDelete},
                success: function (tampil) {
                    if (tampil.hasil == "berhasil") {
                        window.location.reload();
                    }
                }
            })
        })
    })

    $("#id-reset").click(function () {
        $("#searchString").val('');
        $("#form-barang").submit();
    })
</script>