tokosidia/tokosidia/Controllers/CatalogController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Model.Tokosidia;
using ViewModel.Tokosidia;
using Repo.Tokosidia;
using PagedList;

namespace tokosidia.Controllers
{
    [Tokosidia.SessionCheck.SessionCheck]
    public class CatalogController : Controller
    {
        // GET: Catalog
        public ActionResult Index()
        {
            if (Session["name"] == null)
            {
                return Redirect("~/Login/Login/");
            }
            else
            {
                List<M_tbl_Barang> listBarang = new List<M_tbl_Barang>();
                listBarang = BarangRepo.getAllData();

                return View(listBarang);
            }
        }

        public ActionResult Details(int id)
        {
            M_tbl_Barang Barang = new M_tbl_Barang();

            Barang = BarangRepo.getDataById(id);

            return View(Barang);
        }

        [HttpPost]
        public ActionResult Buy(VMTransaksi trnsaksi)
        {
            trnsaksi.Customer_Id = Convert.ToInt16(Session["id_customer"]);
            string result = CatalogRepo.transaksiBarang(trnsaksi);

            if (result == "ok")
            {
                return Json(new { message = "Berhasil" }, JsonRequestBehavior.AllowGet);
            }
            else
            {
                return Json(new { message = "Gagal" }, JsonRequestBehavior.AllowGet);
            }

        }
    }
}

tokosidia/tokosidia/Views/Catalog/Details.cshtml
@model Model.Tokosidia.M_tbl_Barang
@{

    Layout = null;
    //ViewBag.Title = "Edit";
}
<h2>Details Barang</h2>
@using (Html.BeginForm("Buy", "Catalog", FormMethod.Post, new { id = "form-transaksi" }))
{
    <div class="row">
        <div class="col-lg-6">
            <img src="../Images/@Model.img" alt="" height="300px" width="300px" />
        </div>
        <div class="col-lg-6">
            <label>Kode Barang: @Model.Kode_Barang</label><br />
            <label>Nama Barang: @Model.Nama_Barang</label><br />
            <label>Harga: Rp. @Model.Harga</label><br />
            <input type="hidden" name="hargaBarang" id="hargaBarang" value="@Model.Harga" />
            <label>Qty Barang: @Model.Qty</label><br /><br /><br /><br />
            <input type="number" id="Quantity" name="Quantity" />
            <input type="hidden" id="Qty" name="Qty" value="@Model.Qty" />
            <br />
            @Html.ValidationMessageFor(model=>model.Qty , "" , new  {@class = "text-danger" })
            <span style="color:red;display:none" id="validateQty">Pembelian Melebihi Quantity</span>
            <br />
            <button type="submit" id="id-transaksi" value="buy">Buy</button>


            <br><br />
        </div>
    </div>
    <br /><br />
    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>

}

<script>
    $("#id-transaksi").click(function () {
        var qty = $("#Quantity").val();
                var qtyBarang = $("#Qty").val();
                if (parseInt(qty) > parseInt(qtyBarang)) {
                    $("#validateQty").show();

                    return false;
                }
                else {
                    $("#validateQty").hide();
                }
     })

    $("#id-trnsaksi").click(function () {
        var dataForm = $("#id-transaksi").serialize();
        //alert("Button Add call");
        debugger;
        $.ajax({
            url: '/Catalog/Buy',
            data: dataForm,
            method: 'post',
            success: function (response) {
                if (response.message == "Berhasil") {
                    alert(response.message);
                    window.location.reload();
                }
                else {
                    alert(response.message);
                }
            }
        });
    });


</script>

tokosidia/tokosidia/Views/Catalog/Index.cshtml
@model List<Model.Tokosidia.M_tbl_Barang>

<div class="contacts-area mg-b-15">
    <div class="container-fluid">
        <div class="row">
            @foreach (var item in Model)
            {
                <div class="col-lg-3 col-md-6 col-sm-6 col-xs-12">
                    <div class="student-inner-std res-mg-b-30">
                        <div class="student-img">
                            <img src="../Images/@item.img" alt="" />
                        </div>
                        <div class="student-dtl">
                            <h2>@item.Nama_Barang</h2>
                            <p class="dp">Harga: Rp. @item.Harga</p>
                            <br>
                            <button class="btn btn-warning cls-details" id="id-btn-details" idbarang="@item.id_Barang">Details</button>
                        </div>
                    </div>
                </div>
            }
        </div>
    </div>
</div>

<!-- Modal -->
<div class="modal fade bd-example-modal-sm" id="id-modal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header" id="id-header-mods">
                
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body" id="id-body-mods">
                ...
            </div>
            <div class="modal-footer" id="id-footer-mods">
            </div>
        </div>
    </div>
</div>

<script>
    $(".cls-details").click(function () {
        var id_barang = $(this).attr('idBarang');
        //debugger;
        $.ajax({
            url: '@Url.Action("Details", "Catalog")',
            method: 'get',
            data: { id: id_barang },
            success: function (tampil) {
                //debugger;
                //$("#id-title-mods").html("Details");
                $("#id-body-mods").html(tampil);
                $("#id-modal").modal("show");
            }
        });
    })
</script>